(() => {
  "use strict";
  const $=id=>document.getElementById(id), API_URL=String(window.REPORTIA_CONFIG?.API_URL||"").trim();
  const SESSION_KEY="reportia_rcv_session_v51";
  function jsonp(params,timeout=18000){return new Promise((resolve,reject)=>{if(!API_URL)return reject(new Error("Configura API_URL en config.js"));const callback="__r51auth_"+Date.now()+"_"+Math.random().toString(36).slice(2),script=document.createElement("script"),query=new URLSearchParams({...params,callback});const timer=setTimeout(()=>{cleanup();reject(new Error("Tiempo de espera agotado."))},timeout);function cleanup(){clearTimeout(timer);try{delete window[callback]}catch(_){}script.remove()}window[callback]=d=>{cleanup();resolve(d)};script.onerror=()=>{cleanup();reject(new Error("No fue posible conectar con Apps Script."))};script.src=API_URL+(API_URL.includes("?")?"&":"?")+query;document.head.appendChild(script)})}
  function post(params){return fetch(API_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(params)})}
  function initials(name){const p=String(name||"AD").trim().split(/\s+/).filter(Boolean);return((p[0]?.[0]||"A")+(p[1]?.[0]||"D")).toUpperCase()}
  function saveSession(s){localStorage.setItem(SESSION_KEY,JSON.stringify(s))}
  function clearSession(){localStorage.removeItem(SESSION_KEY)}
  function applySession(session){window.REPORTIA_SESSION=session;document.body.classList.add("authenticated");$("secureLogin")?.classList.add("hidden");if($("sessionUser"))$("sessionUser").textContent=session.usuario;if($("sessionAvatar"))$("sessionAvatar").textContent=initials(session.usuario);if($("welcomeUser"))$("welcomeUser").textContent="BIENVENIDO, "+session.usuario.toUpperCase();const isAdmin=session.tipo==="ADMINISTRADOR";document.body.classList.toggle("role-admin",isAdmin);document.body.classList.toggle("role-user",!isAdmin);document.querySelectorAll('[data-admin-only="true"]').forEach(el=>el.style.display=isAdmin?"":"none");document.querySelectorAll('[data-view="upload"]').forEach(el=>{if(!el.classList.contains("view"))el.style.display=isAdmin?"":"none"});const labels={ADMINISTRADOR:"Administrador del sistema",ADMVA:"Área administrativa",COMERCIAL:"Área comercial",ESPECIALIZADO:"Área especializada",GENERAL:"Área general","JEF SERV":"Jefatura de servicio",MANTTO:"Mantenimiento","OP INTERM":"Operación intermedia","OP PRIMERA":"Operación primera","REC HUM":"Recursos humanos"};if($("sessionRole"))$("sessionRole").textContent=(labels[session.tipo]||session.tipo)+(session.gerencia?" · "+session.gerencia:"");setTimeout(()=>window.dispatchEvent(new CustomEvent("reportia:session",{detail:session})),0)}
  async function logout(){const s=window.REPORTIA_SESSION;try{if(window.REPORTIA_PUSH?.unregister)await window.REPORTIA_PUSH.unregister()}catch(_){}if(s?.token)try{await post({accion:'v34_logout',token:s.token,sessionId:s.sessionId||''})}catch(_){}clearSession();location.reload()}
  async function loadUsers(){const select=$("loginUser"),status=$("apiStatus");try{const d=await jsonp({accion:"usuarios"});if(!d?.ok)throw new Error(d?.mensaje||"No fue posible cargar los usuarios.");const users=Array.isArray(d.usuarios)?d.usuarios:[];select.innerHTML='<option value="">Selecciona un usuario</option>'+users.map(u=>`<option value="${String(u.usuario).replace(/"/g,"&quot;")}">${u.usuario} — ${u.tipo}</option>`).join("");status.textContent=`${users.length} usuario(s) disponibles.`;status.className="secure-api-status ok"}catch(e){select.innerHTML='<option value="">No se pudieron cargar los usuarios</option>';status.textContent=e.message;status.className="secure-api-status error"}}
  async function login(){const usuario=$("loginUser").value.trim(),contrasena=$("loginPassword").value,msg=$("loginMessage"),btn=$("loginBtn");if(!usuario||!contrasena){msg.textContent="Selecciona un usuario e ingresa la contraseña.";msg.className="secure-login-message error";return}btn.disabled=true;btn.textContent="Validando acceso…";msg.textContent="";try{const d=await jsonp({accion:"login",usuario,contrasena});if(!d?.ok)throw new Error(d?.mensaje||"Usuario o contraseña incorrectos.");const s={usuario:d.usuario,tipo:String(d.tipo||"USUARIO").toUpperCase(),region:String(d.region||"").toUpperCase(),gerencia:String(d.gerencia||d.tipo||"").toUpperCase(),sessionId:String(d.sessionId||""),token:String(d.token||""),loginAt:new Date().toISOString()};saveSession(s);applySession(s)}catch(e){msg.textContent=e.message;msg.className="secure-login-message error"}finally{btn.disabled=false;btn.textContent="Entrar a REPORT.IA"}}
  async function validateStored(s){try{const d=await jsonp({accion:'v51_session',token:s.token},22000);if(!d?.ok)throw new Error(d?.mensaje||'Sesión no válida');const merged={...s,usuario:d.usuario,tipo:String(d.tipo||s.tipo).toUpperCase(),region:String(d.region||s.region||'').toUpperCase(),gerencia:String(d.gerencia||s.gerencia||'').toUpperCase(),sessionId:String(d.sessionId||s.sessionId||'')};saveSession(merged);applySession(merged)}catch(e){clearSession();location.reload()}}
  function openProfile(){const s=window.REPORTIA_SESSION;if(!s)return;$("v51ProfileUser").textContent=s.usuario;$("v51ProfileRole").textContent=s.tipo;$("v51ProfileRegion").textContent=s.region||'—';$("v51ProfileManager").textContent=s.gerencia||'—';$("v51CurrentPassword").value='';$("v51NewPassword").value='';$("v51ConfirmPassword").value='';$("v51PasswordMsg").textContent='';$("v51ProfileModal").classList.add('open');window.REPORTIA_PUSH?.refreshStatus?.()}
  function closeProfile(){$("v51ProfileModal")?.classList.remove('open')}
  async function changePassword(){const s=window.REPORTIA_SESSION,a=$("v51CurrentPassword").value,n=$("v51NewPassword").value,c=$("v51ConfirmPassword").value,msg=$("v51PasswordMsg"),btn=$("v51ChangePassword");if(!a||!n||!c){msg.textContent='Completa los tres campos.';msg.className='v51-msg error';return}if(n!==c){msg.textContent='La confirmación no coincide.';msg.className='v51-msg error';return}if(n.length<6){msg.textContent='Usa al menos 6 caracteres.';msg.className='v51-msg error';return}btn.disabled=true;msg.textContent='Actualizando contraseña…';msg.className='v51-msg';try{await post({accion:'v51_change_password',token:s.token,actual:a,nueva:n});await new Promise(r=>setTimeout(r,1200));const check=await jsonp({accion:'v51_session',token:s.token}).catch(()=>({ok:false}));if(check?.ok){msg.textContent='No se pudo cambiar. Verifica tu contraseña actual.';msg.className='v51-msg error';return}clearSession();alert('Contraseña actualizada. Por seguridad debes iniciar sesión nuevamente.');location.reload()}finally{btn.disabled=false}}
  $("togglePassword")?.addEventListener("click",()=>{$("loginPassword").type=$("loginPassword").type==="password"?"text":"password"});$("loginBtn")?.addEventListener("click",login);$("loginPassword")?.addEventListener("keydown",e=>{if(e.key==="Enter")login()});$("logoutBtn")?.addEventListener("click",logout);$("v51ProfileBtn")?.addEventListener('click',openProfile);$("v51ProfileClose")?.addEventListener('click',closeProfile);$("v51ProfileBackdrop")?.addEventListener('click',closeProfile);$("v51ChangePassword")?.addEventListener('click',changePassword);
  let session=null;try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch(_){}if(session?.usuario&&session?.token){applySession(session);validateStored(session)}else{clearSession();loadUsers()}
  setInterval(async()=>{const s=window.REPORTIA_SESSION;if(!s?.token)return;try{const d=await jsonp({accion:'v34_heartbeat',token:s.token,sessionId:s.sessionId||''},12000);if(d?.ok===false&&String(d.mensaje||'').toLowerCase().includes('sesión')){clearSession();location.reload()}}catch(_){}},60000);
  window.REPORTIA_AUTH={logout,openProfile,SESSION_KEY};
})();
