(() => {
  "use strict";
  const API_URL=String(window.REPORTIA_CONFIG?.API_URL||'').trim();let messaging=null,swReg=null,currentToken='';
  const $=id=>document.getElementById(id);
  function jsonp(params,timeout=15000){return new Promise((resolve,reject)=>{const cb='__r51push_'+Date.now()+'_'+Math.random().toString(36).slice(2),sc=document.createElement('script'),q=new URLSearchParams({...params,callback:cb}),tm=setTimeout(()=>{clean();reject(new Error('Tiempo de espera agotado.'))},timeout);function clean(){clearTimeout(tm);try{delete window[cb]}catch(_){}sc.remove()}window[cb]=d=>{clean();resolve(d)};sc.onerror=()=>{clean();reject(new Error('Sin conexión con notificaciones.'))};sc.src=API_URL+(API_URL.includes('?')?'&':'?')+q;document.head.appendChild(sc)})}
  function post(params){return fetch(API_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(params)})}
  function configured(){const c=window.REPORTIA_FIREBASE_CONFIG||{};return c.apiKey&&c.projectId&&c.messagingSenderId&&c.appId&&window.REPORTIA_VAPID_KEY&&!String(c.apiKey).includes('PEGA_')}
  async function registerSW(){if(!('serviceWorker'in navigator))throw new Error('Este navegador no admite Service Worker.');if(!swReg)swReg=await navigator.serviceWorker.register('./firebase-messaging-sw.js',{scope:'./'});return swReg}
  async function initMessaging(){if(!configured())throw new Error('Firebase todavía no está configurado en firebase-config.js.');await registerSW();if(!window.firebase)throw new Error('No se cargó Firebase Messaging.');if(!firebase.apps.length)firebase.initializeApp(window.REPORTIA_FIREBASE_CONFIG);messaging=firebase.messaging();messaging.onMessage(payload=>{showForeground(payload);window.dispatchEvent(new CustomEvent('reportia:push',{detail:payload}))});return messaging}
  function showForeground(payload){const data=payload?.data||{},title=data.title||'REPORT.IA',body=data.body||'Tienes una nueva notificación.';const toast=document.createElement('div');toast.className='v51-push-toast';toast.innerHTML=`<b>🔔 ${title}</b><span>${body}</span>`;document.body.appendChild(toast);setTimeout(()=>toast.classList.add('show'),20);setTimeout(()=>{toast.classList.remove('show');setTimeout(()=>toast.remove(),350)},6500);try{window.REPORTIA_REFRESH_NOTIFICATIONS?.()}catch(_){} }
  async function enable(){const s=window.REPORTIA_SESSION;if(!s?.token)throw new Error('Inicia sesión primero.');if(!('Notification'in window))throw new Error('Este navegador no admite notificaciones.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Permiso de notificaciones no concedido.');const m=await initMessaging();currentToken=await m.getToken({vapidKey:window.REPORTIA_VAPID_KEY,serviceWorkerRegistration:swReg});if(!currentToken)throw new Error('No fue posible obtener el token de notificaciones.');await post({accion:'v51_register_push',token:s.token,pushToken:currentToken,deviceLabel:navigator.userAgent.slice(0,120),platform:navigator.platform||''});localStorage.setItem('reportia_push_token_v51',currentToken);await new Promise(r=>setTimeout(r,600));await refreshStatus();return currentToken}
  async function unregister(){const s=window.REPORTIA_SESSION;const pt=currentToken||localStorage.getItem('reportia_push_token_v51')||'';if(s?.token)try{await post({accion:'v51_unregister_push',token:s.token,pushToken:pt})}catch(_){}try{if(messaging&&pt)await messaging.deleteToken()}catch(_){}localStorage.removeItem('reportia_push_token_v51');currentToken='';return true}
  async function refreshStatus(){const s=window.REPORTIA_SESSION,el=$('v51PushStatus'),btn=$('v51EnablePush');if(!s?.token||!el)return;try{const d=await jsonp({accion:'v51_push_status',token:s.token});const perm=('Notification'in window)?Notification.permission:'unsupported';if(!configured()){el.textContent='Pendiente de configurar Firebase';el.className='v51-push-status pending';if(btn)btn.textContent='Configurar después';return}if(perm==='granted'&&Number(d.activos||0)>0){el.textContent='Activas en este usuario · '+d.gerencia;el.className='v51-push-status ok';if(btn)btn.textContent='Reactivar en este dispositivo'}else{el.textContent=perm==='denied'?'Bloqueadas por el navegador':'No activadas en este dispositivo';el.className='v51-push-status '+(perm==='denied'?'error':'pending');if(btn)btn.textContent='Activar notificaciones'}}catch(e){el.textContent=e.message;el.className='v51-push-status error'}}
  async function handleEnable(){const btn=$('v51EnablePush'),msg=$('v51PushMsg');if(btn)btn.disabled=true;if(msg){msg.textContent='Solicitando permiso…';msg.className='v51-msg'}try{await enable();if(msg){msg.textContent='Listo. Este dispositivo recibirá avisos de tu gerencia.';msg.className='v51-msg ok'}}catch(e){if(msg){msg.textContent=e.message;msg.className='v51-msg error'}}finally{if(btn)btn.disabled=false;refreshStatus()}}
  async function autoInit(){if(!window.REPORTIA_SESSION)return;try{await registerSW()}catch(_){}if(configured()&&Notification?.permission==='granted'){try{await initMessaging();currentToken=await messaging.getToken({vapidKey:window.REPORTIA_VAPID_KEY,serviceWorkerRegistration:swReg});if(currentToken){localStorage.setItem('reportia_push_token_v51',currentToken);await post({accion:'v51_register_push',token:window.REPORTIA_SESSION.token,pushToken:currentToken,deviceLabel:navigator.userAgent.slice(0,120),platform:navigator.platform||''})}}catch(_){}}}
  window.addEventListener('reportia:session',()=>autoInit());document.addEventListener('DOMContentLoaded',()=>{$('v51EnablePush')?.addEventListener('click',handleEnable);registerSW().catch(()=>{})});
  window.REPORTIA_PUSH={enable,unregister,refreshStatus,configured};
})();
