(() => {
  'use strict';
  const API_URL=String(window.REPORTIA_CONFIG?.API_URL||'').trim();
  const $=id=>document.getElementById(id);
  const MODULES={gastos:{label:'Gastos',icon:'▤'},costos:{label:'Costos',icon:'$'},productividad:{label:'Productividad',icon:'↗'},general:{label:'General',icon:'◎'}};
  const S={session:null,current:'menu',module:null,local:null,cloud:null,history:[],adminRegion:'',adminSnapshot:''};
  const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
  const upper=s=>norm(s).toUpperCase();
  const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(Number(n)||0);
  const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/\$/g,'').replace(/\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replace(/,/g,'');else if(s.includes(',')&&!s.includes('.')){const p=s.split(',');s=(p[p.length-1].length===2)?p.join('.'):p.join('');}else s=s.replace(/,/g,'');const n=Number(s);return Number.isFinite(n)?n:0};
  const cleanRegion=s=>upper(s).replace(/^RCV\.?\s*REGION\s*/,'').replace(/^REGION\s*/,'').trim();
  // La REGION operativa se obtiene de Jerarquía Sublibro. El encabezado
  // Des Área Gestión JDE queda como respaldo cuando el sublibro no permite
  // reconocer una región de forma inequívoca.
  const REGION_ALIASES=[
    ['COATZACOALCOS',['COATZACOALCOS','COATZAC','COATZ']],
    ['VILLAHERMOSA',['VILLAHERMOSA','VILLA HERMOSA']],
    ['TUXTLA',['TUXTLA GUTIERREZ','TUXTLA']],
    ['TAPACHULA',['TAPACHULA']],
    ['VERACRUZ',['VERACRUZ']],
    ['OAXACA',['OAXACA']],
    ['MERIDA',['MERIDA']],
    ['CANCUN',['CANCUN']],
    ['CAMPECHE',['CAMPECHE']],
    ['CHETUMAL',['CHETUMAL']]
  ];
  function regionFromSubledger(value,fallback=''){
    const u=upper(value);
    for(const [region,aliases] of REGION_ALIASES){
      if(aliases.some(a=>u.includes(a)))return region;
    }
    // Abreviaturas que sólo se usan cuando aparecen como token independiente.
    if(/(^|[ ._\-])VH([ ._\-]|$)/.test(u) && !/[\-]CO[\-]/.test(u))return 'VILLAHERMOSA';
    if(/(^|[ ._\-])TGZ([ ._\-]|$)/.test(u))return 'TUXTLA';
    return cleanRegion(fallback);
  }
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function jsonp(params){return new Promise((resolve,reject)=>{const cb='__rcv34_'+Date.now()+'_'+Math.random().toString(36).slice(2);const sc=document.createElement('script');const q=new URLSearchParams({...params,callback:cb});const timer=setTimeout(()=>{cleanup();reject(new Error('Tiempo de espera agotado.'));},18000);function cleanup(){clearTimeout(timer);try{delete window[cb]}catch(_){}sc.remove()}window[cb]=d=>{cleanup();resolve(d)};sc.onerror=()=>{cleanup();reject(new Error('No fue posible conectar con la nube.'))};sc.src=API_URL+(API_URL.includes('?')?'&':'?')+q;document.head.appendChild(sc)})}
  async function post(params){await fetch(API_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams(params)});return true}
  function build(){if($('rcv34Root'))return;document.body.insertAdjacentHTML('beforeend',`<div id="rcv34Root"><div class="rcv34-shell"><aside class="rcv34-side"><div class="rcv34-brand">REPORT.IA<small>RCV · CONTROL REGIONAL v36</small></div><div class="rcv34-side-user"><strong id="r34User">—</strong><span id="r34Role">—</span></div><div class="rcv34-nav"><button data-r34="menu" class="active">⌂ Menú principal</button><button data-r34="gastos">▤ Gastos</button><button data-r34="costos">$ Costos</button><button data-r34="productividad">↗ Productividad</button><button data-r34="general">◎ General</button><button data-r34="sesiones" class="admin-only">◷ Conexiones</button></div><button id="r34Logout" class="rcv34-logout">↪ Cerrar sesión</button></aside><main class="rcv34-main"><div class="rcv34-top"><div><h1 id="r34Title">Centro de control regional</h1><p id="r34Subtitle">Selecciona un módulo para consultar la información.</p></div><span class="rcv34-region" id="r34Region">—</span></div><section id="r34Panel" class="rcv34-panel active"></section></main></div></div><div id="r34Detail" class="rcv34-detail"><div class="rcv34-detail-card"><div class="rcv34-detail-head"><div><h3 id="r34DetailTitle">Detalle</h3><p id="r34DetailSub"></p></div><button class="rcv34-close" id="r34DetailClose">×</button></div><div id="r34DetailBody"></div></div></div>`);
    document.querySelectorAll('[data-r34]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.r34)));
    $('r34Logout').addEventListener('click',()=>document.getElementById('logoutBtn')?.click());$('r34DetailClose').onclick=()=>$('r34Detail').classList.remove('open');$('r34Detail').addEventListener('click',e=>{if(e.target===$('r34Detail'))$('r34Detail').classList.remove('open')});
  }
  function sessionRegion(s){if(upper(s.tipo)==='ADMINISTRADOR')return 'TODAS LAS REGIONES';return cleanRegion(s.region||s.tipo||'SIN REGIÓN')}
  function navigate(view){S.current=view;document.querySelectorAll('[data-r34]').forEach(b=>b.classList.toggle('active',b.dataset.r34===view));if(view==='menu')return renderMenu();if(view==='sesiones')return renderSessions();return renderModule(view)}
  function renderMenu(){S.module=null;$('r34Title').textContent='Centro de control regional';$('r34Subtitle').textContent=upper(S.session.tipo)==='ADMINISTRADOR'?'Carga, valida, publica y supervisa la consulta regional.':'Consulta exclusivamente la información correspondiente a tu región.';const cards=['gastos','costos','productividad','general'].map(k=>`<article class="rcv34-menu-card" data-open="${k}"><div class="ico">${MODULES[k].icon}</div><h3>${MODULES[k].label}</h3><p>${k==='general'?'Vista consolidada de los indicadores más recientes.':'Consulta real, presupuesto, semáforo y detalle por jerarquía.'}</p><div class="status">ABRIR MÓDULO →</div></article>`).join('');$('r34Panel').innerHTML=`<div class="rcv34-menu-grid">${cards}</div>`;document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>navigate(x.dataset.open))}
  function status(module,real,budget){if(module==='productividad')return real>=budget?'green':'red';const ar=Math.abs(real),ab=Math.abs(budget);return ar<=ab?'green':'red'}
  function periodLabel(rows){const ps=[...new Set(rows.map(r=>r.period).filter(Boolean))];return ps.length?`${ps[0]}${ps.length>1?' – '+ps[ps.length-1]:''}`:'Periodo del archivo'}
  function totals(rows,module){const real=rows.reduce((a,r)=>a+(Number(r.real)||0),0),budget=rows.reduce((a,r)=>a+(Number(r.budget)||0),0);return{real,budget,diff:module==='productividad'?real-budget:Math.abs(real)-Math.abs(budget),st:status(module,real,budget)}}
  function findHeader(arr,module){let best=-1,score=-1;for(let i=0;i<Math.min(50,arr.length);i++){const rr=(arr[i]||[]).map(upper);const toks=module==='productividad'?['JERARQUIA','REAL','PRESUPUESTO']:['CUENTA','JERARQUIA','PERIODO','REAL','PRESUPUESTO'];const s=toks.reduce((n,t)=>n+(rr.some(x=>x.includes(t))?1:0),0);if(s>score){score=s;best=i}}return best}
  function idx(headers,alts){const hs=headers.map(upper);for(const a of alts){let i=hs.findIndex(x=>x===a);if(i>=0)return i;i=hs.findIndex(x=>x.includes(a));if(i>=0)return i}return-1}
  function inferRegion(arr){for(let i=0;i<Math.min(12,arr.length);i++){const row=arr[i]||[];for(let j=0;j<row.length;j++){if(upper(row[j]).includes('AREA GESTION JDE')||upper(row[j]).includes('ÁREA GESTIÓN JDE')){for(let k=j+1;k<row.length;k++)if(norm(row[k]))return cleanRegion(row[k]);}}}return''}
  async function parseFile(file,module){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',raw:true,cellDates:true});let all=[];for(const sn of wb.SheetNames){const arr=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:'',raw:true});if(!arr.length)continue;const hr=findHeader(arr,module);if(hr<0)continue;const h=(arr[hr]||[]).map(norm);const baseRegion=inferRegion(arr);const iRegion=idx(h,['REGION','REGIÓN','AREA GESTION JDE']);const iHier=idx(h,['JERARQUIA CUENTA CONTABLE','JERARQUÍA CUENTA CONTABLE']);const iAccount=idx(h,['DES CUENTA CONTABLE','CUENTA CONTABLE','JERARQUIA CUENTA CONTABLE']);const iSubHierarchy=idx(h,['JERARQUIA SUBLIBRO','JERARQUÍA SUBLIBRO']);const iSub=idx(h,['ULTIMO NIVEL DE SL','ÚLTIMO NIVEL DE SL']);const iBUCode=idx(h,['JERARQUIA UNIDAD DE NEGOCIO JDE','JERARQUÍA UNIDAD DE NEGOCIO JDE']);const iBU=idx(h,['JERARQUIA UNIDAD DE NEGOCIO JDE EN','JERARQUÍA UNIDAD DE NEGOCIO JDE EN','UNIDAD DE NEGOCIO']);const iPeriod=idx(h,['PERIODO','MES']);let iReal=-1,iBudget=-1;const H=h.map(upper);if(module==='productividad'){iReal=H.findIndex(x=>x.includes('REAL GESTION'));iBudget=H.findIndex(x=>x.includes('PRESUPUESTO GESTION'));}else{const realCols=H.map((x,i)=>x.includes('REAL GESTION')?i:-1).filter(i=>i>=0);const budCols=H.map((x,i)=>x.includes('PRESUPUESTO GESTION')?i:-1).filter(i=>i>=0);iReal=realCols.length>1?realCols[realCols.length-1]:realCols[0];iBudget=budCols.length>1?budCols[budCols.length-1]:budCols[0];}
      for(const r of arr.slice(hr+1)){if(!r.some(v=>norm(v)))continue;const subHierarchy=norm(iSubHierarchy>=0?r[iSubHierarchy]:'');const fallbackRegion=cleanRegion(iRegion>=0?r[iRegion]:baseRegion);const region=regionFromSubledger(subHierarchy,fallbackRegion);const hierarchy=norm(iHier>=0?r[iHier]:'SIN JERARQUÍA')||'SIN JERARQUÍA';const account=norm(iAccount>=0?r[iAccount]:hierarchy)||hierarchy;const real=num(iReal>=0?r[iReal]:0),budget=num(iBudget>=0?r[iBudget]:0);if(!region&&real===0&&budget===0)continue;all.push({region:region||'SIN REGIÓN',hierarchy,account,subledger:norm(iSub>=0?r[iSub]:subHierarchy),subledgerHierarchy:subHierarchy,businessUnitCode:norm(iBUCode>=0?r[iBUCode]:''),businessUnit:norm(iBU>=0?r[iBU]:''),period:norm(iPeriod>=0?r[iPeriod]:''),real,budget,sourceSheet:sn});}}
    if(!all.length)throw new Error('No se encontró una estructura reconocible en el archivo.');
    // Algunos JD exportan PRESUPUESTO 2026 como entero con 4 decimales implícitos
    // (ej. 1157030227 representa 115703.0227). Detectamos esa escala por columna.
    if(module!=='productividad'){
      const ratios=all.filter(r=>Math.abs(r.real)>1&&Math.abs(r.budget)>1).slice(0,500).map(r=>Math.abs(r.budget)/Math.abs(r.real)).sort((a,b)=>a-b);
      const median=ratios.length?ratios[Math.floor(ratios.length/2)]:1;
      if(median>1000)all.forEach(r=>r.budget=r.budget/10000);
    }
    return{module,filename:file.name,uploadedLocalAt:new Date().toISOString(),rows:all,regions:[...new Set(all.map(r=>r.region))],period:periodLabel(all)} }
  function groupRows(rows,key){const m=new Map();rows.forEach(r=>{const k=r[key]||'SIN CLASIFICAR';if(!m.has(k))m.set(k,[]);m.get(k).push(r)});return m}
  function filterRegion(data){if(!data?.rows)return[];if(upper(S.session.tipo)==='ADMINISTRADOR'){const reg=cleanRegion(S.adminRegion||'');return reg?data.rows.filter(r=>cleanRegion(r.region)===reg):data.rows;}const reg=sessionRegion(S.session);return data.rows.filter(r=>cleanRegion(r.region)===reg)}
  function adminRegionLabel(){return upper(S.session.tipo)==='ADMINISTRADOR'?(S.adminRegion||'TODAS LAS REGIONES'):sessionRegion(S.session)}
  function populateRegionFilter(data){const sel=$('r34RegionFilter');if(!sel||upper(S.session.tipo)!=='ADMINISTRADOR')return;const regions=[...new Set((data?.rows||[]).map(r=>cleanRegion(r.region)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));const keep=S.adminRegion;sel.innerHTML='<option value="">Todas las regiones</option>'+regions.map(r=>`<option value="${esc(r)}">${esc(r)}</option>`).join('');if(keep&&regions.includes(keep))sel.value=keep;else{S.adminRegion='';sel.value='';}sel.onchange=()=>{S.adminRegion=cleanRegion(sel.value);if(S.cloud){const box=$('r34Data');if(box){box.innerHTML=publicationCard(S.cloudMeta||{});renderData(S.cloud,S.module,S.cloudMeta||{});}}}}
  function publicationCard(meta){return `<div class="rcv34-card rcv34-publication-card"><h3>Publicación oficial</h3><p>Actualizada: ${esc(meta?.fecha||'—')} · Por: ${esc(meta?.usuario||'—')} ${meta?.snapshotId?'· ID '+esc(meta.snapshotId.slice(0,8)):''}</p></div>`}
  function sema(st){return `<span class="rcv34-semaforo rcv34-${st}"><i class="rcv34-dot"></i>${st==='green'?'VERDE · BIEN':'ROJO · REQUIERE ACCIÓN'}</span>`}
  function renderData(data,module,meta={}){const host=$('r34Data')||$('r34Panel'),rows=filterRegion(data);if(!rows.length){host.insertAdjacentHTML('beforeend',`<div class="rcv34-empty">No hay información disponible para ${upper(S.session.tipo)==='ADMINISTRADOR'?(S.adminRegion?'la región '+esc(S.adminRegion):'el filtro seleccionado'):'esta región'}.</div>`);return}const t=totals(rows,module);const groups=groupRows(rows,'hierarchy');const bad=[...groups].filter(([,rs])=>totals(rs,module).st==='red').length;const head=`<div class="rcv34-kpis"><article class="rcv34-kpi"><small>REAL</small><strong>${money(t.real)}</strong><span>${data.period||periodLabel(rows)}</span></article><article class="rcv34-kpi"><small>PRESUPUESTO</small><strong>${money(t.budget)}</strong><span>Presupuesto acumulado</span></article><article class="rcv34-kpi"><small>VARIACIÓN</small><strong>${money(t.diff)}</strong><span>${module==='productividad'?'Real - presupuesto':'Exceso absoluto vs presupuesto'}</span></article><article class="rcv34-kpi"><small>SEMÁFORO</small><strong>${sema(t.st)}</strong><span>${bad} jerarquía(s) en rojo</span></article></div>`;const items=[...groups].sort((a,b)=>Math.abs(totals(b[1],module).real)-Math.abs(totals(a[1],module).real)).map(([name,rs])=>{const z=totals(rs,module);return`<article class="rcv34-break-item ${z.st==='red'?'is-red':'is-green'}" data-hierarchy="${esc(name)}"><div class="rcv34-break-top"><strong>${esc(name)}</strong>${sema(z.st)}</div><div class="amounts"><span>Real<b>${money(z.real)}</b></span><span>Presupuesto<b>${money(z.budget)}</b></span></div></article>`}).join('');host.insertAdjacentHTML('beforeend',head+`<article class="rcv34-card"><h3>Detalle por jerarquía</h3><p>Selecciona una jerarquía. Al abrir una jerarquía se muestran primero únicamente los conceptos del mismo color de su semáforo; usa "Ver todos" para consultar el resto.</p><div class="rcv34-breakdown">${items}</div></article>`);host.querySelectorAll('[data-hierarchy]').forEach(el=>el.onclick=()=>openHierarchy(data,module,el.dataset.hierarchy,meta))}
  function openHierarchy(data,module,hierarchy,meta){
    const rows=filterRegion(data).filter(r=>r.hierarchy===hierarchy),t=totals(rows,module);
    const redRows=rows.filter(r=>status(module,r.real,r.budget)==='red');
    const greenRows=rows.filter(r=>status(module,r.real,r.budget)==='green');
    const initial=t.st==='red'?redRows:greenRows;
    const stateLabel=t.st==='red'?'rojo':'verde';
    $('r34DetailTitle').textContent=hierarchy;
    $('r34DetailSub').textContent=`${MODULES[module].label} · ${adminRegionLabel()} · ${data.period||''}`;
    const makeRows=list=>list.map(r=>`<tr data-row-status="${status(module,r.real,r.budget)}"><td>${esc(r.account)}</td><td>${esc(r.subledgerHierarchy||r.subledger)}</td><td>${esc(r.businessUnit)}</td><td>${esc(r.period)}</td><td>${money(r.real)}</td><td>${money(r.budget)}</td><td>${sema(status(module,r.real,r.budget))}</td></tr>`).join('');
    let plan='';
    if(t.st==='red'&&meta.snapshotId){plan=`<div class="rcv34-plan"><strong>Plan de mejora / acción correctiva</strong><p>Describe qué se hará para corregir esta desviación.</p><textarea id="r34PlanText" placeholder="Escribe aquí el plan de mejora..."></textarea><div class="rcv34-plan-actions"><span id="r34PlanMsg" class="rcv34-msg"></span><button id="r34SavePlan" class="rcv34-btn primary">Guardar plan de mejora</button></div></div>`}
    $('r34DetailBody').innerHTML=`<div class="rcv34-kpis"><article class="rcv34-kpi"><small>REAL</small><strong>${money(t.real)}</strong></article><article class="rcv34-kpi"><small>PRESUPUESTO</small><strong>${money(t.budget)}</strong></article><article class="rcv34-kpi"><small>VARIACIÓN</small><strong>${money(t.diff)}</strong></article><article class="rcv34-kpi"><small>ESTADO</small><strong>${sema(t.st)}</strong></article></div><div class="rcv34-detail-filter"><div><strong>Conceptos en ${stateLabel}</strong><span>${initial.length} en ${stateLabel} de ${rows.length} movimientos</span></div><div class="rcv34-detail-filter-actions"><button class="rcv34-filter-btn active" id="r34OnlyState">● Solo ${stateLabel}s</button><button class="rcv34-filter-btn" id="r34ShowAll">Ver todos</button></div></div><div class="rcv34-table-wrap"><table class="rcv34-table"><thead><tr><th>Cuenta / concepto</th><th>Jerarquía Sublibro</th><th>Unidad de negocio</th><th>Periodo</th><th>Real</th><th>Presupuesto</th><th>Estado</th></tr></thead><tbody id="r34DetailRows">${makeRows(initial)}</tbody></table></div>${plan}`;
    $('r34Detail').classList.add('open');
    $('r34OnlyState').onclick=()=>{$('r34DetailRows').innerHTML=makeRows(initial);$('r34OnlyState').classList.add('active');$('r34ShowAll').classList.remove('active')};
    $('r34ShowAll').onclick=()=>{$('r34DetailRows').innerHTML=makeRows(rows);$('r34ShowAll').classList.add('active');$('r34OnlyState').classList.remove('active')};
    if($('r34SavePlan'))$('r34SavePlan').onclick=()=>savePlan(module,meta.snapshotId,hierarchy)
  }
  async function savePlan(module,snapshotId,hierarchy){const txt=$('r34PlanText').value.trim(),msg=$('r34PlanMsg');if(!txt){msg.textContent='Escribe el plan de mejora.';msg.className='rcv34-msg error';return}msg.textContent='Guardando…';try{await post({accion:'v34_plan',token:S.session.token,module,snapshotId,region:sessionRegion(S.session),hierarchy,texto:txt});msg.textContent='Plan de mejora enviado correctamente.';msg.className='rcv34-msg ok';$('r34SavePlan').disabled=true}catch(e){msg.textContent=e.message;msg.className='rcv34-msg error'}}
  async function renderModule(module){S.module=module;S.local=null;S.cloud=null;S.adminRegion='';S.adminSnapshot='';$('r34Title').textContent=MODULES[module].label;$('r34Subtitle').textContent=module==='general'?'Consolidado de la publicación más reciente de cada módulo.':'Información filtrada automáticamente por región.';const admin=upper(S.session.tipo)==='ADMINISTRADOR';if(module==='general')return loadGeneral();$('r34Panel').innerHTML=`<div class="rcv34-section-head"><div><h2>${MODULES[module].label}</h2><p>${admin?'Procesa un archivo, valida el resultado y publícalo. También puedes revisar una región o una publicación anterior.':'Consulta la última publicación oficial disponible.'}</p></div><div class="rcv34-actions"><button id="r34Refresh" class="rcv34-btn">↻ Actualizar nube</button></div></div>${admin?`<div class="rcv34-admin-filters"><div><label>Región</label><select id="r34RegionFilter" class="rcv34-history-select"><option value="">Todas las regiones</option></select></div><div><label>Fecha de publicación</label><select id="r34History" class="rcv34-history-select"><option value="">Más reciente</option></select></div><button id="r34ClearFilters" class="rcv34-btn">Limpiar filtros</button></div>`:''}<div class="rcv34-upload"><div class="rcv34-upload-row"><input type="file" id="r34File" accept=".xlsx,.xls"><button id="r34Process" class="rcv34-btn">Procesar archivo</button><button id="r34Publish" class="rcv34-btn primary" disabled>☁ Publicar en nube</button></div><div id="r34UploadMsg" class="rcv34-msg">Carga exclusivamente el archivo de ${MODULES[module].label}.</div></div><div id="r34Data"></div>`;$('r34Refresh').onclick=()=>loadCloud(module,S.adminSnapshot);if(admin){$('r34Process').onclick=()=>processSelected(module);$('r34Publish').onclick=()=>publishLocal(module);$('r34ClearFilters').onclick=()=>{S.adminRegion='';S.adminSnapshot='';if($('r34RegionFilter'))$('r34RegionFilter').value='';if($('r34History'))$('r34History').value='';loadCloud(module)};loadHistory(module)}loadCloud(module)}
  async function processSelected(module){const file=$('r34File').files?.[0],msg=$('r34UploadMsg');if(!file){msg.textContent='Selecciona un archivo Excel.';msg.className='rcv34-msg error';return}msg.textContent='Procesando y validando…';try{S.local=await parseFile(file,module);msg.textContent=`Validado: ${S.local.rows.length.toLocaleString()} registros · Región(es): ${S.local.regions.join(', ')}`;msg.className='rcv34-msg ok';$('r34Publish').disabled=false;$('r34Data').innerHTML='<div class="rcv34-card"><h3>Vista previa local</h3><p>Esta información todavía no ha sido publicada en la nube.</p></div>';renderData(S.local,module,{})}catch(e){msg.textContent=e.message;msg.className='rcv34-msg error';$('r34Publish').disabled=true}}
  async function publishLocal(module){if(!S.local)return;const b=$('r34Publish'),msg=$('r34UploadMsg');b.disabled=true;msg.textContent='Publicando…';try{await post({accion:'v34_upload',token:S.session.token,module,payload:JSON.stringify(S.local)});msg.textContent='Publicación enviada. Actualizando información oficial…';msg.className='rcv34-msg ok';setTimeout(()=>{loadCloud(module);loadHistory(module)},1200)}catch(e){msg.textContent=e.message;msg.className='rcv34-msg error';b.disabled=false}}
  async function loadCloud(module,snapshotId=''){const box=$('r34Data');if(!box)return;box.innerHTML='<div class="rcv34-empty">Consultando información oficial…</div>';try{const d=await jsonp({accion:snapshotId?'v34_snapshot':'v34_module',token:S.session.token,module,snapshotId});if(!d?.ok)throw new Error(d?.mensaje||'No fue posible consultar.');if(!d.disponible){box.innerHTML='<div class="rcv34-empty">Aún no hay una publicación disponible para este módulo.</div>';return}S.cloud=d.data;S.cloudMeta=d.meta||{};S.adminSnapshot=snapshotId||'';populateRegionFilter(S.cloud);box.innerHTML=publicationCard(S.cloudMeta);renderData(S.cloud,module,S.cloudMeta)}catch(e){box.innerHTML=`<div class="rcv34-empty">${esc(e.message)}</div>`}}
  async function loadHistory(module){const sel=$('r34History');if(!sel)return;try{const d=await jsonp({accion:'v34_history',token:S.session.token,module});if(!d?.ok)return;S.history=d.items||[];sel.innerHTML='<option value="">Más reciente</option>'+S.history.map(x=>`<option value="${esc(x.snapshotId)}">${esc(x.fecha)} · ${esc(x.usuario)}${(x.regiones||[]).length?' · '+esc((x.regiones||[]).join(', ')):''}</option>`).join('');sel.value=S.adminSnapshot||'';sel.onchange=()=>{S.adminSnapshot=sel.value||'';loadCloud(module,S.adminSnapshot)}}catch(_){}}
  async function loadGeneral(){$('r34Panel').innerHTML='<div class="rcv34-empty">Construyendo consolidado regional…</div>';try{const d=await jsonp({accion:'v34_general',token:S.session.token});if(!d?.ok)throw new Error(d?.mensaje||'No fue posible cargar el consolidado.');let html='<div class="rcv34-menu-grid">';for(const m of ['gastos','costos','productividad']){const x=d.modules?.[m];if(!x?.disponible){html+=`<article class="rcv34-menu-card"><div class="ico">${MODULES[m].icon}</div><h3>${MODULES[m].label}</h3><p>Sin publicación disponible.</p></article>`;continue}const rows=x.data.rows||[],t=totals(rows,m);html+=`<article class="rcv34-menu-card" data-general-open="${m}"><div class="ico">${MODULES[m].icon}</div><h3>${MODULES[m].label}</h3><p>Real: <b>${money(t.real)}</b><br>Presupuesto: <b>${money(t.budget)}</b></p><div class="status">${sema(t.st)}</div></article>`}html+='</div>';$('r34Panel').innerHTML=html;document.querySelectorAll('[data-general-open]').forEach(x=>x.onclick=()=>navigate(x.dataset.generalOpen))}catch(e){$('r34Panel').innerHTML=`<div class="rcv34-empty">${esc(e.message)}</div>`}}
  async function renderSessions(){if(upper(S.session.tipo)!=='ADMINISTRADOR')return renderMenu();$('r34Title').textContent='Conexiones y actividad';$('r34Subtitle').textContent='Control de accesos y tiempo de consulta de los usuarios.';$('r34Panel').innerHTML='<div class="rcv34-empty">Consultando sesiones…</div>';try{const d=await jsonp({accion:'v34_sessions',token:S.session.token});if(!d?.ok)throw new Error(d?.mensaje||'No fue posible consultar sesiones.');const active=d.items.filter(x=>x.estado==='ACTIVA').length,total=d.items.length,mins=d.items.reduce((a,x)=>a+(Number(x.minutos)||0),0);const trs=d.items.map(x=>`<tr><td>${esc(x.usuario)}</td><td>${esc(x.region)}</td><td>${esc(x.inicio)}</td><td>${esc(x.ultimaActividad)}</td><td>${esc(x.fin||'—')}</td><td>${Number(x.minutos||0).toFixed(1)} min</td><td>${Number(x.consultas||0)}</td><td>${Number(x.planes||0)}</td><td>${esc(x.estado)}</td></tr>`).join('');$('r34Panel').innerHTML=`<div class="rcv34-session-summary"><article class="rcv34-kpi"><small>SESIONES REGISTRADAS</small><strong>${total}</strong></article><article class="rcv34-kpi"><small>ACTIVAS / RECIENTES</small><strong>${active}</strong></article><article class="rcv34-kpi"><small>TIEMPO ACUMULADO</small><strong>${mins.toFixed(0)} min</strong></article></div><article class="rcv34-card"><h3>Bitácora de conexiones</h3><p>Una sesión sin cierre explícito se considera desconectada según su última actividad.</p><div class="rcv34-table-wrap"><table class="rcv34-table"><thead><tr><th>Usuario</th><th>Región</th><th>Inicio</th><th>Última actividad</th><th>Fin</th><th>Duración</th><th>Consultas</th><th>Planes</th><th>Estado</th></tr></thead><tbody>${trs}</tbody></table></div></article>`}catch(e){$('r34Panel').innerHTML=`<div class="rcv34-empty">${esc(e.message)}</div>`}}
  function init(session){build();S.session=session;$('r34User').textContent=session.usuario;$('r34Role').textContent=upper(session.tipo)==='ADMINISTRADOR'?'Administrador del sistema':`Región ${sessionRegion(session)}`;$('r34Region').textContent=sessionRegion(session);renderMenu()}
  window.addEventListener('reportia:session',e=>init(e.detail));if(window.REPORTIA_SESSION)init(window.REPORTIA_SESSION);
})();
